name: CI
on:
  # push: {}
  workflow_dispatch:
env:
  LIBVIPS_TAG: v8.18.3
  RELEASE_TAG: v8.18.3
permissions: {}
jobs:
  build:
    permissions:
      contents: read
      # packages: read
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: libvips/build-win64-mxe
          ref: ${{ env.LIBVIPS_TAG }}
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Checkout custom repository
        uses: actions/checkout@v6
        with:
          path: custom
      - name: Apply common patches
        run: |
          node ./custom/patch-common.js
      - name: Pull base image
        run: docker pull ghcr.io/libvips/build-win64-mxe:latest
      - name: Build
        run: ./build.sh -r ${{ env.LIBVIPS_TAG }} -t x86_64-w64-mingw32.static -t i686-w64-mingw32.static -t aarch64-w64-mingw32.static vips-web
      - name: Collect artifacts
        shell: bash
        run: |

          mkdir -p release

          find packaging -maxdepth 1 -type f -name "*.zip" | while read -r file; do
            cp "$file" "release/$(basename "$file")"
          done

          echo "Artifacts collected:"
          ls -la release || true

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: libvips
          path: release/*
          retention-days: 1

  release:
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: release

      - name: Flatten files
        shell: bash
        run: |
          mkdir -p final
          find release -type f -exec cp {} final/ \;
          echo "Final files:"
          ls -la final || true

      - name: Create Release (in this repo)
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          overwrite_files: true
          body: |
            ## Automated libvips build (${{ env.LIBVIPS_TAG }})

            **Source Repository:** [libvips/build-win64-mxe](https://github.com/libvips/build-win64-mxe)
          files: final/*
          prerelease: false