name: CI
on:
  push:
  workflow_dispatch:
env:
  LIBVIPS_TAG: v8.18.2
permissions: {}
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      source_sha: ${{ steps.ver.outputs.source_sha }}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: libvips/build-win64-mxe
          ref: ${{ env.LIBVIPS_TAG }}

      - name: Compute version/tag from source SHA
        id: ver
        shell: bash
        run: |
          SHA="$(git -C source rev-parse --short=7 HEAD)"
          echo "source_sha=${SHA}" >> "$GITHUB_OUTPUT"
  build:
    needs: [prepare]
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: libvips/build-win64-mxe
          ref: ${{ env.LIBVIPS_TAG }}
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Checkout custom repository
        uses: actions/checkout@v6
        with:
          path: custom
      - name: Apply common patches
        run: |
          node ./custom/patch-common.js
      #- name: Pull base image
      #  run: docker pull ghcr.io/libvips/build-win64-mxe:latest
      #- run: ./build.sh -r ${{ env.LIBVIPS_TAG }} -t x86_64-w64-mingw32.shared
      - run: ls --recursive
  release:
    needs: [build]
    if: ${{ false }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: release

      - name: Flatten files
        shell: bash
        run: |
          mkdir -p final
          find release -type f -exec cp {} final/ \;
          echo "Final files:"
          ls -la final || true

      - name: Create Release (in this repo)
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.prepare.outputs.tag }}
          name: OpenComic-${{ needs.prepare.outputs.tag }}
          body: |
            ## Automated libvips build

            **Source Repository:** [libvips/build-win64-mxe](https://github.com/libvips/build-win64-mxe)
            **Commit:** https://github.com/ollm/OpenComic/commit/${{ needs.prepare.outputs.source_sha }}

            ### Changes Since Last Nightly:
            https://github.com/ollm/OpenComic/compare/${{ needs.prepare.outputs.last_sha }}...${{ needs.prepare.outputs.source_sha }}
          files: final/*
          prerelease: false